name: autoyapf

on: 
  pull_request:
    branches: 
      - master
    paths:
      - '**.py'
 
jobs:
  label:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8.10]
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{github.head_ref}}
          fetch-depth: 0
      - uses: dorny/paths-filter@v2
        id: changed
        with:
          filters: |
            blog:
              - 'codedigger/blog/**'
            codedigger:
              - 'codedigger/codedigger/**'
            codeforces:
              - 'codedigger/codeforces/**'
            contest:
              - 'codedigger/contest/**'
            lists:
              - 'codedigger/lists/**'
            problem:
              - 'codedigger/problem/**'
            user:
              - 'codedigger/user/**'
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Installing PEP8 blog
        if: steps.changes.outputs.blog == 'true'
        run: |
          python -m pip install --upgrade pip
          pip install yapf
          yapf -i -r -vv -p codedigger/blog/
          # URL="https://api.github.com/repos/${{github.repository}}/pulls/${{ github.event.pull_request.number }}/files?per_page=100"
          # FILES=$(curl -s -X GET -G $URL | jq -r '.[] | .filename')
          # echo $FILES
      - name: Installing PEP8 codedigger
        if: steps.changes.outputs.codedigger == 'true'
        run: |
          python -m pip install --upgrade pip
          pip install yapf
          yapf -i -r -vv -p codedigger/codedigger/
          # URL="https://api.github.com/repos/${{github.repository}}/pulls/${{ github.event.pull_request.number }}/files?per_page=100"
          # FILES=$(curl -s -X GET -G $URL | jq -r '.[] | .filename')
          # echo $FILES
      - name: Installing PEP8 codeforces
        if: steps.changes.outputs.codeforces == 'true'
        run: |
          python -m pip install --upgrade pip
          pip install yapf
          yapf -i -r -vv -p codedigger/codeforces/
          # URL="https://api.github.com/repos/${{github.repository}}/pulls/${{ github.event.pull_request.number }}/files?per_page=100"
          # FILES=$(curl -s -X GET -G $URL | jq -r '.[] | .filename')
          # echo $FILES
      - name: Installing PEP8  contest
        if: steps.changes.outputs.contest == 'true'
        run: |
          python -m pip install --upgrade pip
          pip install yapf
          yapf -i -r -vv -p codedigger/contest/
          # URL="https://api.github.com/repos/${{github.repository}}/pulls/${{ github.event.pull_request.number }}/files?per_page=100"
          # FILES=$(curl -s -X GET -G $URL | jq -r '.[] | .filename')
          # echo $FILES
      - name: Installing PEP8 lits
        if: steps.changes.outputs.lists == 'true'
        run: |
          python -m pip install --upgrade pip
          pip install yapf
          yapf -i -r -vv -p codedigger/lists/
          # URL="https://api.github.com/repos/${{github.repository}}/pulls/${{ github.event.pull_request.number }}/files?per_page=100"
          # FILES=$(curl -s -X GET -G $URL | jq -r '.[] | .filename')
          # echo $FILES
      - name: Installing PEP8 problem 
        if: steps.changes.outputs.problem == 'true'
        run: |
          python -m pip install --upgrade pip
          pip install yapf
          yapf -i -r -vv -p codedigger/problem/
          # URL="https://api.github.com/repos/${{github.repository}}/pulls/${{ github.event.pull_request.number }}/files?per_page=100"
          # FILES=$(curl -s -X GET -G $URL | jq -r '.[] | .filename')
          # echo $FILES
      - name: Installing PEP8 user
        if: steps.changes.outputs.user == 'true'
        run: |
          python -m pip install --upgrade pip
          pip install yapf
          yapf -i -r -vv -p codedigger/user/
          # URL="https://api.github.com/repos/${{github.repository}}/pulls/${{ github.event.pull_request.number }}/files?per_page=100"
          # FILES=$(curl -s -X GET -G $URL | jq -r '.[] | .filename')
          # echo $FILES
      - name: Check for modified files
        id: git-check
        run: |
          echo ::set-output name=modified::$(if git diff-index --quiet HEAD --; then echo "false"; else echo "true"; fi)
      - name: Git Push Changes
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "refactor: automatic code reformatting to PEP8 by yapf"
          git push 
