name: Create Issue Branch

on:
  issues:
    types: [ assigned ]
  issue_comment:
    types: [ created ]
  pull_request:
    types: [ closed ]

jobs:
  create_issue_branch_job:
    runs-on: ubuntu-latest
    steps:
      - name: Create Issue Branch
        uses: robvanderleek/create-issue-branch@main
        mode: chatops
        gitSafeReplacementChar: '-'
        defaultBranch: 'master'
        autoCloseIssue: true
        branchName: 'issue-${issue.number}/${issue.title,}'
        branches:
          - label: enhancement
            prefix: feature/${issue.user.login}/
          - label: bug
            prefix: bugfix/${issue.user.login}/
          - label: refactor
            prefix: refactor/${issue.user.login}/
          - label: documentation
            prefix: docs/${issue.user.login}/
          - label: '*'
            prefix: issues/${issue.user.login}/
        experimental:
          branchNameArgument: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
